### ISSUE TITLE
Could we nerf this cause it's like cheating

### ISSUE THREAD

**Issue by Ankasi57** [attickdoor/XIVComboPlugin#51] opened 2021-07-09 22:09 UTC
Title, this feels like cheating because it's suffering the same effect that macro chainer did, where it enabled you to repeat macros over and over again, it's like botting and an unfair advantage to players.

**Comment by Carighan** [comment] 2021-07-10 06:44
I don't see the advantage other than on a physical level.

You do the same thing with 1 button that you'd usually do with 3. But there's **no** intelligence in it. If you previously pressed, say, 1, then 2, then 3, you now press 1, then 1, then 1. That's all it does. I hope that explains why it doesn't actually change any gameplay/input.

And why it is still useful? Because some of us suffer from issues with our wrists/fingers. The less we have to move them, the better. Hence being okay with just the 1-6 keys + 2 buttons on the mouse for modifiers where usually I'd need ~twice as many on some of my jobs, that's **amazing**. Essentially turns the game from a pain (quite literally) to playable during lvl80 fights.

**Comment by Ankasi57** [comment] 2021-07-10 22:18
See that's the thing, the issue lies within the same fault that macro recursion/macro chainer and I don't feel like it's rightly fair for this thing to exist when the same issue was brought up with macro chainer and they fixed it in a fair method.

**Comment by Carighan** [comment] 2021-07-11 20:06
Oh, I think you're confused. This cannot fire off abilities on its own, it's a one-press-per-ability thing. I finally realized what you are talking about, and yeah, infinite macro size was a problem

But that's a wholly different functionality. Did you mean to post in the issues of a different Dalamud plugin?

**Comment by Ankasi57** [comment] 2021-07-11 20:07
Oh I see now, it doesn't auto press a combo string, terribly sorry! I figured it would've done the auto pressing of all combos and felt like that was a thing. Sorry sorry.

**Comment by Apoxiosis** [comment] 2021-07-17 02:55
this mod literally works the same way pvp skills and duty skills work without mods. the game does this for you unmodded but in limited scenarios. id hope that one day SE updates the game to work that way everywhere. it feels arbitrary and almost punishing for controller players to have to waste 3 skill slots on 1 combo when youre never using 2 of the skills unless you use the first skill in the chain first.

**Comment by Asinin3** [comment] 2021-07-17 13:13
It is a huge advantage over playing without. You can have one keybind for 4 actions, that even dynamically changes if you get a proc. This means you can mindlessly spam one button allowing you to pay far more attention to boss mechanics, have far less keybinds making it easier to weave ogcd's or use movement keys while doing rotation. And less need to pay attention to procs or hotbar. It also makes controller players far better. There's a reason it's not in the game by default.

Removing the ability for people to accidentally push the wrong button in a combo, raises the skill floor and greatly helps bad players especially, but also good players as they can pay far more attention to a bosses mechanics or have keybinds that are far easier to press (e.g avoid using any shift+ modifiers).

**Comment by providence42** [comment] 2021-07-17 15:28
I get your concerns. But others using the Plug-In does not affect you or your gameplay experience in any way.

**Comment by Asinin3** [comment] 2021-07-17 23:14
It does, this is an MMO. If people in your group use it, you may get to clear a boss fight you otherwise may not have. If you don't use this or other tools like cactbot's timers for boss mechanics then you're effectively shooting yourself in the foot compared to other players who are making use of the tools. It effectively lowers the difficulty of the game, even if you and your party doesn't use it, you will effectively see more players with the high-end gear which lowers the exclusivity of having the items if you get them yourself, or lowers the perceived difficulty.

**Comment by Asinin3** [comment] 2021-07-17 23:30
I would personally be far more okay with this if it didn't change buttons when procs occur, as I feel like that is just far too much of an advantage in terms of allowing players to focus very little on what they do for their rotation.

**Comment by Carighan** [comment] 2021-07-19 06:26
Procs aren't handled different than other abilities, though: "Is there -EVER- a reason to do X without first doing Y? No? Then X might as well turn into Y."

The reasoning for this is simple, the game itself in fact dictates it when you go into PvP, and virtually all these combos are just copies from PvP, where stuff works exactly that way. And what will eventually make it into PvE as rising hotbar needs start to exceed 3 hotbars.

Mind you, not everyone here has healthy hands. Reducing the need for hand movement to just 1-6 + A/Q/W/R/T/G + modifiers is a godsend because it makes the game playable in the first place. PvP would be, exactly because it uses the same combo actions. PvE doesn't, but luckily there's mods such as this one to enable the same functionality there. There's no reason for abilities that require exactly 0 intelligence to use in sequence to not be a single button, and PvP shows how much the game doesn't change from collapsing them - as does this mod.

For the procs, you can **blindly** mash the proc button before hitting the proccing button (say Fan Dance 3 before every Fan Dance 2 or 1) and you just emulated this mod, because... well... that's exactly what it does. >.> 

If you feel this makes the game much easier, other than motor requirements from reaching further across the keyboard or money requirements buying an MMO mouse, then I would argue you assign **way** too much intellectual importance to procs and sequences. Like I said, you can just blindly mash the button. Same effect.

**Comment by Asinin3** [comment] 2021-07-24 13:45
>Procs aren't handled different than other abilities, though: "Is there -EVER- a reason to do X without first doing Y? No? Then X might as well turn into Y."

Procs require you actually pay attention to them while doing a rotation while dodging boss mechanics, it is absolutely making it easier to play the game if you can spam one button and not worry about procs and just focus on the boss mechanics.
>it makes the game playable in the first place

Confirming that the game is harder to play without the tool and that this helps you play the game.
>PvP would be, exactly because it uses the same combo actions. PvE doesn't, but luckily there's mods such as this one to enable the same functionality there.

The fact that PvP has the system, and they didn't add it to PvE is irrelevant, this is a third party tool, and it gives you a big 
advantage over other players, and isn't how the game was designed. If FFXIV had this system inbuilt for PvE then you would be on the same playing field as other players at the very least. But content would also likely be tuned to be harder.

**Comment by Apoxiosis** [comment] 2021-07-24 17:14
this dude is hell bent on making the game impossible to play for people with disabilities. its sad. 

just stop talking to him

**Comment by Difjob** [comment] 2021-07-25 00:59
This plugin does not in ANY way allow you to spam one button and win. It does not weave in offcooldowns or anything like that. It will not activate procs. It will not apply DoTs. It might put your 2 or 3 skill combo on 1 button but you still have to press other abilities inbetween every activation. If you just spammed your combo then you're doing to do terrible.

What this does do is save on keybinds and hotbar space. There is no difference between pressing 1, 4, 5, 2, 6, 7, 3, 8, 9 and pressing 1, 4, 5, 1, 6, 7, 1, 8, 9. Takes the same time, takes just as many skill presses and takes just as much hand motor skill to perform.

It's the same.

**Comment by Asinin3** [comment] 2021-07-25 03:53
>this dude is hell bent on making the game impossible to play for people with disabilities. its sad.

Then why don't you complain to SE about them making the game too hard for people with disabilities? Why rely on a third party tool to make the game easier and put yourself on an uneven playing field compared to everyone else who aren't breaking the ToS by using such a tool. Bringing up people with disabilities as an excuse for the tool to exist isn't doing yourself any favors.

>What this does do is save on keybinds and hotbar space. There is no difference between pressing 1, 4, 5, 2, 6, 7, 3, 8, 9 and pressing 1, 4, 5, 1, 6, 7, 1, 8, 9. Takes the same time, takes just as many skill presses and takes just as much hand motor skill to perform.

How is it the same, you literally cannot make a mistake when doing the normal chain rotation abilities with this tool. For bad players who mess it up especially while doing boss mechanics, it is an absolute crutch they can use to rely on rather than getting better. Even good players can mess up their rotation from time to time when dodging mechanics and dealing with a slew of other things happening. This tool makes it impossible. And its very clear more motor skills are required when you have more buttons to push, especially when you consider without this tool people are going to have more modifier keys e.g shift.

So:
q(chain1) > 1(ogcd) > e(chain2) > 2(ogcd) > shift+q(chain3) > 3(ogcd) > shift+e(aoe1) > shift+r(aoe2) > shift+e(aoe1) > shift+r(aoe2)
combo becomes:
q >1(ogcd) > q > 2(ogcd) > q(chain3) > 3(ogcd) > e(aoe1) > e(aoe2) > e(aoe1) > e(aoe2)

Your delusional if you think this doesn't require less hand-motor skills. Especially when hard bosses with lots of mechanics are going on. And with the way it works on procs it's even more of an advantage and allows you to pay far less attention to them. With this tool you can spam 1-2 buttons while weaving ogcd's for the majority of your rotation.

>The only advantage it gives is that you don't need to keep track of which combo step you're on... but the game literally shows you which step you're on by lighting up the next skill anyway so there's still no real difference.

Except now you literally cannot fuck up the order lets say your on step 2 of a chain then run out of some aoe and are focused on what the boss is doing then run in and instinctively push 1 again because thas what you normally do when running in. The tool will just push the right button for you. I don't know how it's hard to understand that this is a crutch for bad players to rely on. Unless you're not being genuine.

**Comment by Apoxiosis** [comment] 2021-07-25 04:27
> No need to be disingenuous and bring up disabled people 

im not being disingenuous. im a disabled gamer and cant use keyboards. this plugin is just a quality of life addon. i still had to earn my rotation and perform my positionals and do mechanics. what ive found iin the past however is players who think theyre better than they really are tend to have issues with things that others dont. as many people have said this addon doesnt play the game for you it doesnt make decisions or use ogcds or control your character to not die in aoes. failure is still an option with pcombo. youre just out here acting like an asshole for no reason.

**Comment by Asinin3** [comment] 2021-07-25 04:29
Just going to add that I think the tool isn't as bad for controller players to use as they are already quite handi-capped due to lack of buttons compared to KB+M. HOWEVER, since the tool is PC Only, you're at a massive advantage compared to console players.

**Comment by Apoxiosis** [comment] 2021-07-25 04:45
so your solution is to get pcombo nerfed instead of advocating for square to implement it baseline everywhere like they did in pvp? youre a real piece of work.

**Comment by Asinin3** [comment] 2021-07-25 04:48
I never said that square shouldn't implement this. If they do then my concerns would be nullified as everyone would be on the same playing field. In fact, if you read my earlier comment I said this earlier:

> this is a third party tool, and it gives you a big advantage over other players, and isn't how the game was designed. If FFXIV had this system inbuilt for PvE then you would be on the same playing field as other players at the very least. But content would also likely be tuned to be harder.

**Comment by Apoxiosis** [comment] 2021-07-25 04:51
lets also not forget you can do the same thing with macros as well. 

the game is playable without it --even by people in my position. i did it, i learned my rotation and everything without it. pcombo is just quality of life. consolidated abilities on the actionbar. youre acting like it guarantees success because it makes it "impossible to mess up your main rotation". you shouldnt be messing up in the first place. with or without pcombo.

**Comment by Asinin3** [comment] 2021-07-25 05:12
> lets also not forget you can do the same thing with macros as well.

You can't. Macros were handi-capped on-purpose by square so they are slower and you will lose damage by clipping gcd. They also cannot be queued so players with latency can't buffer them. So this point is really going against your argument when the developer of the game purposefully didn't want this to be possible to macro a rotation and made it slow on purpose.

**Comment by Apoxiosis** [comment] 2021-07-25 05:15
the developer of the game also literally added pcombo to the game in pvp and quest duties where you play as other characters, so kinda weird hill t odie on. i just dont get why youre so bent out of shape over it. it doesnt do anything you claim it does.

**Comment by Asinin3** [comment] 2021-07-25 05:53
The developer of the game literally added it to the game but didn't allow you to use it in PvE* - Pretty obvious that if they have it in the game, and didn't add it to PvE it was on purpose.

>it doesnt do anything you claim it does.
Explain what points I said it does that it doesn't actually do.

**Comment by Carighan** [comment] 2021-07-25 08:05
> The developer of the game literally added it to the game but didn't allow you to use it in PvE* - Pretty obvious that if they have it in the game, and didn't add it to PvE it was on purpose.

Quite the opposite in fact. They're steadily adding more and more combos to the game, it's just a slow process. But ignoring PvP even, the game is quite clearly headed to the collapsed-ability/procs destination. Basically any time they touch an ability now they also collapse it while they're at it.

So yeah, if anything the mod is quite progressive. It shows you how FFXIV's own implementation will be in a few years.

(Which would be awesome btw, I'd be happy to no longer need this mod)

**Comment by Asinin3** [comment] 2021-07-26 03:33
I went ahead and tried it out and i could hold strafe key while turning my camera with right-click+mouse in order to circle strafe a target dummy and perform my **entire** rotation, even weaving ogcd's as a ninja. The fact that you can have complete freedom of movement while doing a rotation, and use up far less buttons meaning less shift/ctrl modifiers or keypresses to switch hotbars means far less complexity in pulling off your rotation. Oh and it also makes it impossible to make a mistake with the chain combo's.

It's a very clear advantage over players not using this tool, and even works on ogcd abilities like dream > assassinate as a ninja. 

>So yeah, if anything the mod is quite progressive.

Don't pretend like the tool isn't giving people an unfair advantage in a multiplayer game. While If square implemented it I would have far less issues since everyone would have the ability to use it. - It is cheating, what part of not allowed with ToS makes that questionable? Just look at other posts online about how this tool is giving you an advantage, it is not just me making this claim.

**Comment by Carighan** [comment] 2021-07-26 08:26
Hrm, I'm more surprised you couldn't do this without the mod. I'm sorry, but I can't state that any more nicely. :(

**Comment by providence42** [comment] 2021-07-26 14:36
> Ah yes the old, i don't have anything I can say against your claims, so your bad. Despite **you** being the one using a bannable third-party tool to make the game easier and almost certainly lying about being disabled.
> 
> Regardless, doing a rotation while strafing isn't hard if you have keybinds that work well for it. E.g keybind the strafe to a mouse side-button and then your left hand is completely free to do a rotation.

of all the things in your live/environment that you could rant on and make a change, you chose this.
it baffles me how people like you make it in society. this is not intended as an attack of any kind, I am just genuinely shocked. 
Again, whoever uses this tool, it DOES NOT interfere with you in game experience at all. IT DOES NOT!

**Comment by Asinin3** [comment] 2021-07-26 15:30
>  it DOES NOT interfere with you in game experience at all. IT DOES NOT.
> for you to say that it does, shows that you haven't played endgame/savage content, a clear will almost never depend on 1 guy alone.

Who said only one player is using it? Many savage/ultimate groups are running with people using cactbot to display all the timers for mechanics, this tool to make it easier to do their rotation, the xiv alexander mod to allow themselves to play like they have 0ms. To triple weave and a bunch of other shit. It's not just one tool that makes the content easier, it's all of them.

And, it absolutely does affect the game. It's an MMO. Imagine competing with friends or hell, world first as to who can clear content faster only for them to beat you due to using these tools. And it's only available on PC for people who aren't scared of being banned due to breaking ToS. Luckily XIV isn't a game where you can take PvE gear into PvP, and this tool isn't useful in PvP because if it was it would be far more ridiculous.

The only reason I wasted so much time replying here is because people kept saying it doesn't help you play the game when it clearly does. At the very least own up to the fact that it helps you. I initially only meant to say how I think the fact that it works on proc-based abilities is far too much of an advantage.

**Comment by Carighan** [comment] 2021-07-26 16:56
Hold on, it doesn't work in competitive! And as with ACT, the moment you start using mods for anything **but** personal use, it becomes a bannable offense. As long as you use it on a personal-only level, the devs are "fine" with it, in so far that it doesn't impact others - naturally - and you're not being an asshole to someone about it.

And I agree, it's fine if someone wants to use a mod like this to change their own game to be more accessible to **them**. But the moment someone goes "If you join my group and you don't have these 15 Dalamud mods enabled you get kicked!" it crosses a line and it's IMO a bannable offense.

Personal modification that just flat out doesn't affect other people is fine, OTOH. It's like a difficulty setting in any other game, don't like it, don't use it. Everyone can pick what settings they like. Is it technically still against the ToS? Yeah, sure. But it's also not something that ought to ever be observable outside, so in a black box scenario it wouldn't exist, and that's where the devs usually draw the line. Especially in regards to discussing it with other players, or worse trying to get them to use mods.

**Comment by daemitus** [comment] 2021-07-27 00:14
In a competitive environment, this and ACT are usually broken for a week due to patches anyways.

**Comment by Asinin3** [comment] 2021-07-27 02:40
>And as with ACT, the moment you start using mods for anything but personal use, it becomes a bannable offense. 

It's only bannable if you're caught. There has been some players banned for it as they were streaming while doing world first races with it on-screen. But if they weren't streaming (Or they used OBS Game capture so it didn't show the overlay window) then they wouldn't have been banned. I think this is besides the point. Cheaters don't care about rules unless what they're using is detectable.

I also do not see competitive environments as only the first few days of content before a patch. Getting high parses/speed runs is competitive content. So is competing with friends, so is actually clearing an ultimate or savage. And this tool helps in those situations.

**Comment by lovelydumpling** [comment] 2021-08-21 16:57
I feel like this issue can be closed, as OP's post was resolved as a misunderstanding of what the plugin did.

Anyway, I _am_ one of the disabled people using this mod and I appreciate it immensely. I'm not really of the mind to care whether it gives me some kind of small advantage or not, I appreciate that it lets me play the game at all without causing me the physical pain I have without it. I really want Square Enix to implement this system into the game directly, but until then I'm going to use this and I'm not going to apologize for it.

**Closed** 2021-09-16 23:07 UTC
